// const CSV_PATH = path.join(process.cwd(), 'public', 'data.csv')

interface DataItem {
  [key: string]: string | number
}

const mockedData: DataItem[] = [
  {
    "Numero Recibo": "2020/0357",
    "Periodo Inicio": "19/05/2020",
    "Periodo Fin": "27/07/2020",
    "Consumo Agua (m³)": 5.0,
    "Costo Agua (€)": 36.5,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 13.5,
    "Consumo Energia Frio (MWh)": 1.399,
    "Costo Energia Frio (€)": 85.44,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 4.5,
    "Costo Total (€)": 135.44,
  },
  {
    "Numero Recibo": "2020/0377",
    "Periodo Inicio": "27/07/2020",
    "Periodo Fin": "22/09/2020",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 42.5,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 13.5,
    "Consumo Energia Frio (MWh)": 1.268,
    "Costo Energia Frio (€)": 77.58,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 4.5,
    "Costo Total (€)": 133.58,
  },
  {
    "Numero Recibo": "2020/0398",
    "Periodo Inicio": "22/09/2020",
    "Periodo Fin": "19/11/2020",
    "Consumo Agua (m³)": 7.0,
    "Costo Agua (€)": 48.5,
    "Consumo Energia Calor (MWh)": 0.812,
    "Costo Energia Calor (€)": 62.22,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 1.5,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 4.5,
    "Costo Total (€)": 112.22,
  },
  {
    "Numero Recibo": "2021/0075",
    "Periodo Inicio": "19/11/2020",
    "Periodo Fin": "22/01/2021",
    "Consumo Agua (m³)": 9.0,
    "Costo Agua (€)": 60.5,
    "Consumo Energia Calor (MWh)": 2.732,
    "Costo Energia Calor (€)": 177.42,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 3.0,
    "Costo Total (€)": 237.92,
  },
  {
    "Numero Recibo": "2021/0262",
    "Periodo Inicio": "22/01/2021",
    "Periodo Fin": "23/03/2021",
    "Consumo Agua (m³)": 8.0,
    "Costo Agua (€)": 54.5,
    "Consumo Energia Calor (MWh)": 1.591,
    "Costo Energia Calor (€)": 108.96,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 3.0,
    "Costo Total (€)": 163.46,
  },
  {
    "Numero Recibo": "2021/0422",
    "Periodo Inicio": "23/03/2021",
    "Periodo Fin": "24/05/2021",
    "Consumo Agua (m³)": 7.0,
    "Costo Agua (€)": 48.5,
    "Consumo Energia Calor (MWh)": 0.624,
    "Costo Energia Calor (€)": 50.94,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 3.0,
    "Costo Total (€)": 99.44,
  },
  {
    "Numero Recibo": "2021/0510",
    "Periodo Inicio": "24/05/2021",
    "Periodo Fin": "23/07/2021",
    "Consumo Agua (m³)": 4.0,
    "Costo Agua (€)": 30.5,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 13.5,
    "Consumo Energia Frio (MWh)": 1.159,
    "Costo Energia Frio (€)": 71.04,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 4.5,
    "Costo Total (€)": 115.04,
  },
  {
    "Numero Recibo": "2021/0529",
    "Periodo Inicio": "23/07/2021",
    "Periodo Fin": "22/09/2021",
    "Consumo Agua (m³)": 3.0,
    "Costo Agua (€)": 24.5,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 13.5,
    "Consumo Energia Frio (MWh)": 0.982,
    "Costo Energia Frio (€)": 60.42,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 4.5,
    "Costo Total (€)": 98.42,
  },
  {
    "Numero Recibo": "2021/0557",
    "Periodo Inicio": "22/09/2021",
    "Periodo Fin": "22/11/2021",
    "Consumo Agua (m³)": 7.0,
    "Costo Agua (€)": 48.5,
    "Consumo Energia Calor (MWh)": 0.798,
    "Costo Energia Calor (€)": 61.38,
    "Consumo Energia Frio (MWh)": 0.07,
    "Costo Energia Frio (€)": 4.2,
    "Fijo Encendido Caldera ACS (€)": 5.0,
    "Fijo Encendido Caldera Calefacción (€)": 12.0,
    "Cuota Servicio (€)": 3.0,
    "Costo Total (€)": 114.08,
  },
  {
    "Numero Recibo": "2022/0101",
    "Periodo Inicio": "22/11/2021",
    "Periodo Fin": "21/01/2022",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 2.249,
    "Costo Energia Calor (€)": 246.5,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 318.1,
  },
  {
    "Numero Recibo": "2022/0330",
    "Periodo Inicio": "21/01/2022",
    "Periodo Fin": "22/03/2022",
    "Consumo Agua (m³)": 7.0,
    "Costo Agua (€)": 81.6,
    "Consumo Energia Calor (MWh)": 1.765,
    "Costo Energia Calor (€)": 198.1,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 279.7,
  },
  {
    "Numero Recibo": "2022/0560",
    "Periodo Inicio": "22/03/2022",
    "Periodo Fin": "23/05/2022",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.795,
    "Costo Energia Calor (€)": 101.1,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 172.7,
  },
  {
    "Numero Recibo": "2022/0650",
    "Periodo Inicio": "23/05/2022",
    "Periodo Fin": "20/07/2022",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 21.6,
    "Consumo Energia Frio (MWh)": 1.45,
    "Costo Energia Frio (€)": 145.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 238.2,
  },
  {
    "Numero Recibo": "2022/0852",
    "Periodo Inicio": "20/07/2022",
    "Periodo Fin": "22/09/2022",
    "Consumo Agua (m³)": 3.0,
    "Costo Agua (€)": 35.8,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 21.6,
    "Consumo Energia Frio (MWh)": 1.15,
    "Costo Energia Frio (€)": 145.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 235.6,
  },
  {
    "Numero Recibo": "2022/0990",
    "Periodo Inicio": "22/09/2022",
    "Periodo Fin": "22/11/2022",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.698,
    "Costo Energia Calor (€)": 149.6,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 254.4,
  },
  {
    "Numero Recibo": "2023/0102",
    "Periodo Inicio": "22/11/2022",
    "Periodo Fin": "20/01/2023",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 2.014,
    "Costo Energia Calor (€)": 314.9,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 419.7,
  },
  {
    "Numero Recibo": "2023/0354",
    "Periodo Inicio": "20/01/2023",
    "Periodo Fin": "22/03/2023",
    "Consumo Agua (m³)": 5.0,
    "Costo Agua (€)": 59.5,
    "Consumo Energia Calor (MWh)": 1.478,
    "Costo Energia Calor (€)": 230.2,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 322.9,
  },
  {
    "Numero Recibo": "2023/0565",
    "Periodo Inicio": "22/03/2023",
    "Periodo Fin": "23/05/2023",
    "Consumo Agua (m³)": 5.0,
    "Costo Agua (€)": 59.5,
    "Consumo Energia Calor (MWh)": 0.697,
    "Costo Energia Calor (€)": 127.8,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 220.5,
  },
  {
    "Numero Recibo": "2023/0650",
    "Periodo Inicio": "23/05/2023",
    "Periodo Fin": "19/07/2023",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 21.6,
    "Consumo Energia Frio (MWh)": 1.45,
    "Costo Energia Frio (€)": 145.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 238.2,
  },
  {
    "Numero Recibo": "2023/0815",
    "Periodo Inicio": "19/07/2023",
    "Periodo Fin": "20/09/2023",
    "Consumo Agua (m³)": 3.0,
    "Costo Agua (€)": 35.8,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 21.6,
    "Consumo Energia Frio (MWh)": 1.15,
    "Costo Energia Frio (€)": 115.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 205.6,
  },
  {
    "Numero Recibo": "2023/0995",
    "Periodo Inicio": "20/09/2023",
    "Periodo Fin": "22/11/2023",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.798,
    "Costo Energia Calor (€)": 149.6,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 254.4,
  },
  {
    "Numero Recibo": "2024/0105",
    "Periodo Inicio": "22/11/2023",
    "Periodo Fin": "22/01/2024",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 2.02,
    "Costo Energia Calor (€)": 314.9,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 419.7,
  },
  {
    "Numero Recibo": "2024/0330",
    "Periodo Inicio": "22/01/2024",
    "Periodo Fin": "22/03/2024",
    "Consumo Agua (m³)": 7.0,
    "Costo Agua (€)": 81.6,
    "Consumo Energia Calor (MWh)": 1.678,
    "Costo Energia Calor (€)": 298.1,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 402.9,
  },
  {
    "Numero Recibo": "2024/0560",
    "Periodo Inicio": "22/03/2024",
    "Periodo Fin": "22/05/2024",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.995,
    "Costo Energia Calor (€)": 151.1,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 255.9,
  },
  {
    "Numero Recibo": "2024/0750",
    "Periodo Inicio": "22/05/2024",
    "Periodo Fin": "19/07/2024",
    "Consumo Agua (m³)": 6.0,
    "Costo Agua (€)": 71.6,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 21.6,
    "Consumo Energia Frio (MWh)": 1.45,
    "Costo Energia Frio (€)": 145.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 238.2,
  },
  {
    "Numero Recibo": "2024/1955",
    "Periodo Inicio": "19/07/2024",
    "Periodo Fin": "20/09/2024",
    "Consumo Agua (m³)": 3.0,
    "Costo Agua (€)": 35.8,
    "Consumo Energia Calor (MWh)": 0.0,
    "Costo Energia Calor (€)": 21.6,
    "Consumo Energia Frio (MWh)": 1.15,
    "Costo Energia Frio (€)": 115.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.2,
    "Costo Total (€)": 205.6,
  },
  {
    "Numero Recibo": "2024/2057",
    "Periodo Inicio": "20/09/2024",
    "Periodo Fin": "19/11/2024",
    "Consumo Agua (m³)": 5.0,
    "Costo Agua (€)": 81.74,
    "Consumo Energia Calor (MWh)": 0.348,
    "Costo Energia Calor (€)": 36.54,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.48,
    "Costo Total (€)": 118.28,
  },
  {
    "Numero Recibo": "2025/0385",
    "Periodo Inicio": "19/11/2024",
    "Periodo Fin": "22/01/2025",
    "Consumo Agua (m³)": 9.0,
    "Costo Agua (€)": 121.79,
    "Consumo Energia Calor (MWh)": 1.594,
    "Costo Energia Calor (€)": 162.73,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.58,
    "Costo Total (€)": 284.52,
  },
  {
    "Numero Recibo": "2025/2291",
    "Periodo Inicio": "22/01/2025",
    "Periodo Fin": "21/03/2025",
    "Consumo Agua (m³)": 0.0,
    "Costo Agua (€)": 31.79,
    "Consumo Energia Calor (MWh)": 1.635,
    "Costo Energia Calor (€)": 165.29,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.58,
    "Costo Total (€)": 197.08
  },
  {
    "Numero Recibo": "2025/4140",
    "Periodo Inicio": "21/03/2025",
    "Periodo Fin": "20/05/2025",
    "Consumo Agua (m³)": 4.0,
    "Costo Agua (€)": 40.0,
    "Consumo Energia Calor (MWh)": 0.706,
    "Costo Energia Calor (€)": 70.60,
    "Consumo Energia Frio (MWh)": 0.0,
    "Costo Energia Frio (€)": 0.0,
    "Fijo Encendido Caldera ACS (€)": 10.0,
    "Fijo Encendido Caldera Calefacción (€)": 20.0,
    "Cuota Servicio (€)": 3.58,
    "Costo Total (€)": 144.18
  }


]

export async function fetchAndProcessData() {
  return new Promise<{
    data: DataItem[]
    changes: { [key: string]: { current: number; previous: number; change: number } }
  }>((resolve) => {
    const data = mockedData

    // Ordenar los datos por fecha (asumiendo que el formato de fecha es dd/mm/yyyy)
    data.sort((a, b) => {
      const dateA = new Date(a["Periodo Fin"].split("/").reverse().join("-"))
      const dateB = new Date(b["Periodo Fin"].split("/").reverse().join("-"))
      return dateA.getTime() - dateB.getTime()
    })

    const currentPeriod = data[data.length - 1]
    const currentPeriodEndDate = new Date(currentPeriod["Periodo Fin"].split("/").reverse().join("-"))

    // Encontrar el período equivalente del año anterior
    const previousPeriod =
      data.find((item) => {
        const itemEndDate = new Date(item["Periodo Fin"].split("/").reverse().join("-"))
        return (
          itemEndDate.getMonth() === currentPeriodEndDate.getMonth() &&
          itemEndDate.getFullYear() === currentPeriodEndDate.getFullYear() - 1
        )
      }) || data[data.length - 2]

    const calculateChange = (current: number, previous: number) =>
      previous !== 0 ? ((current - previous) / previous) * 100 : 0

    const fieldsToCompare = [
      "Consumo Agua (m³)",
      "Costo Agua (€)",
      "Consumo Energia Calor (MWh)",
      "Costo Energia Calor (€)",
      "Consumo Energia Frio (MWh)",
      "Costo Energia Frio (€)",
      "Fijo Encendido Caldera ACS (€)",
      "Fijo Encendido Caldera Calefacción (€)",
      "Cuota Servicio (€)",
      "Costo Total (€)",
    ]

    const changes = fieldsToCompare.reduce(
      (acc, field) => {
        const current = Number(currentPeriod[field])
        const previous = Number(previousPeriod[field])
        acc[field] = {
          current,
          previous,
          change: calculateChange(current, previous),
        }
        return acc
      },
      {} as { [key: string]: { current: number; previous: number; change: number } },
    )

    resolve({
      data,
      changes,
    })
  })
}

